Добавил раздачу по HTTP и HTTPS по выбору, а так же указание сети через env-файл

diff --git a/docker-deploy/Dockerfile b/docker-deploy/Dockerfile
--- a/docker-deploy/Dockerfile
+++ b/docker-deploy/Dockerfile
@@ -26,3 +26,15 @@ FROM nginx:${NGINX_RELEASE:-1.27-alpine-slim}
 
 COPY --from=build /home/node/front/dist /frontend-dist
 COPY --from=build /home/node/front/docker-deploy/nginx/templates /etc/nginx/templates
+COPY --from=build /home/node/front/docker-deploy/nginx/nginx.conf /etc/nginx/nginx.conf
+
+# generate config for http or https to nginx
+ARG HTTP_NGINX_CONFIG
+ARG HTTPS_NGINX_CONFIG
+
+# substitute ${HTTP_NGINX_CONFIG} and ${HTTPS_NGINX_CONFIG} into default.conf.template
+RUN if [ -z "${HTTP_NGINX_CONFIG}" ] && [ -z "${HTTPS_NGINX_CONFIG}" ]; then \
+      echo "HTTP_NGINX_CONFIG or HTTPS_NGINX_CONFIG must be set. Unknown error"; \
+      exit 1; \
+    fi && \
+    envsubst < /etc/nginx/templates/default.conf.template > /etc/nginx/templates/default.conf.template.substututed && mv /etc/nginx/templates/default.conf.template.substututed /etc/nginx/templates/default.conf.template
